import { useQuery } from "@tanstack/react-query";
import { useRoute } from "wouter";
import type { Analysis, User } from "@shared/schema";
import { Markdown } from "@/lib/markdown";
import { formatDateTime, riskColor, toTitleCase } from "@/lib/format";
import { Logo } from "@/components/Logo";
import { Button } from "@/components/ui/button";
import { Printer, ArrowLeft } from "lucide-react";
import { Link } from "wouter";
import { ProfessionVisual } from "@/components/ProfessionVisual";

export default function Report() {
  const [, params] = useRoute("/report/:id");
  const id = params?.id ? Number(params.id) : null;
  const { data: analysis, isLoading } = useQuery<Analysis>({
    queryKey: ["/api/analyses", id],
    enabled: !!id,
  });
  const { data: me } = useQuery<User>({ queryKey: ["/api/me"] });

  if (isLoading || !analysis) {
    return (
      <div className="min-h-screen grid place-items-center text-muted-foreground">Loading report…</div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="no-print sticky top-0 z-10 bg-background/90 backdrop-blur border-b border-border">
        <div className="max-w-3xl mx-auto px-6 py-3 flex items-center justify-between">
          <Link href="/history">
            <Button variant="ghost" size="sm" data-testid="button-report-back">
              <ArrowLeft className="w-4 h-4 mr-1.5" />
              Back
            </Button>
          </Link>
          <Logo size={22} />
          <Button onClick={() => window.print()} size="sm" data-testid="button-print">
            <Printer className="w-4 h-4 mr-1.5" />
            Save as PDF
          </Button>
        </div>
      </div>

      <article className="max-w-3xl mx-auto px-6 py-10">
        <header className="mb-6 print-card">
          <div className="flex items-center gap-2 text-xs uppercase tracking-widest text-muted-foreground mb-3">
            <span className="text-gradient font-semibold">CareerProof AI</span>
            <span>·</span>
            <span>AI Impact Assessment</span>
          </div>
          <h1 className="text-2xl font-semibold tracking-tight leading-tight" data-testid="text-report-job-title">
            {toTitleCase(analysis.job_title)}
          </h1>
          <div className="text-sm text-muted-foreground mt-2 flex flex-wrap gap-x-4 gap-y-1">
            <span>{formatDateTime(analysis.created_date)}</span>
            {me && <span>Prepared for {me.full_name}</span>}
            <span>Provider: {displayProvider(analysis.provider_used)}</span>
          </div>
          <div className="mt-4">
            <span
              className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-xs font-medium ${riskColor(analysis.automation_risk)}`}
            >
              {analysis.automation_risk} automation potential · {analysis.risk_score}/100
            </span>
          </div>
          <div className="mt-5">
            <ProfessionVisual
              key={`${analysis.id}-${analysis.job_title}-${analysis.job_description}`}
              title={analysis.job_title}
              description={analysis.job_description}
              compact
            />
          </div>
        </header>

        <section>
          <Markdown source={analysis.result_text} locked={Boolean(analysis.is_locked)} />
        </section>

        <footer className="mt-10 pt-4 border-t border-border text-xs text-muted-foreground">
          Generated by CareerProof AI · {window.location.host} · {formatDateTime(analysis.created_date)}
        </footer>
      </article>

      <button
        className="no-print fixed bottom-6 right-6 rounded-full bg-primary text-primary-foreground shadow-lg px-4 py-2.5 text-sm font-medium flex items-center gap-2 hover-elevate"
        onClick={() => window.print()}
        data-testid="button-print-floating"
      >
        <Printer className="w-4 h-4" />
        Print / Save as PDF
      </button>
    </div>
  );
}

function displayProvider(provider: string) {
  return provider === "MockInvokeLLM" ? "AI Career Impact Model" : provider;
}
