import { useQuery } from "@tanstack/react-query";
import { useRoute } from "wouter";
import type { Analysis, User } from "@shared/schema";
import { formatDateTime, toTitleCase } from "@/lib/format";
import { Logo } from "@/components/Logo";
import { Button } from "@/components/ui/button";
import { Printer, ArrowLeft } from "lucide-react";
import { Link } from "wouter";
import { VisualReport } from "@/components/VisualReport";

export default function Report() {
  const [, params] = useRoute("/report/:id");
  const id = params?.id ? Number(params.id) : null;
  const { data: analysis, isLoading } = useQuery<Analysis>({
    queryKey: ["/api/analyses", id],
    enabled: !!id,
  });
  const { data: me } = useQuery<User>({ queryKey: ["/api/me"] });

  if (isLoading || !analysis) {
    return (
      <div className="min-h-screen grid place-items-center text-muted-foreground">Loading report…</div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="no-print sticky top-0 z-10 bg-background/90 backdrop-blur border-b border-border">
        <div className="max-w-5xl mx-auto px-6 py-3 flex items-center justify-between">
          <Link href="/history">
            <Button variant="ghost" size="sm" data-testid="button-report-back">
              <ArrowLeft className="w-4 h-4 mr-1.5" />
              Back
            </Button>
          </Link>
          <Logo size={22} />
          <Button onClick={() => window.print()} size="sm" data-testid="button-print">
            <Printer className="w-4 h-4 mr-1.5" />
            Save as PDF
          </Button>
        </div>
      </div>

      <article className="max-w-5xl mx-auto px-4 sm:px-6 py-8 sm:py-10">
        <header className="mb-5 print-card text-xs uppercase tracking-widest text-muted-foreground flex flex-wrap gap-x-3 gap-y-1">
          <span className="text-gradient font-semibold">CareerProof AI</span>
          <span aria-hidden>·</span>
          <span>AI Impact Assessment</span>
          <span aria-hidden>·</span>
          <span>{toTitleCase(analysis.job_title)}</span>
          {me && (
            <>
              <span aria-hidden>·</span>
              <span>Prepared for {me.full_name}</span>
            </>
          )}
        </header>

        <VisualReport analysis={analysis} locked={Boolean(analysis.is_locked)} />

        <footer className="mt-10 pt-4 border-t border-border text-xs text-muted-foreground">
          Generated by CareerProof AI · {window.location.host} · {formatDateTime(analysis.created_date)}
        </footer>
      </article>

      <button
        className="no-print fixed bottom-6 right-6 rounded-full bg-primary text-primary-foreground shadow-lg px-4 py-2.5 text-sm font-medium flex items-center gap-2 hover-elevate"
        onClick={() => window.print()}
        data-testid="button-print-floating"
      >
        <Printer className="w-4 h-4" />
        Print / Save as PDF
      </button>
    </div>
  );
}
