import { useQuery } from "@tanstack/react-query";
import { useRoute } from "wouter";
import type { Analysis, User } from "@shared/schema";
import { formatDateTime, toTitleCase } from "@/lib/format";
import { Logo } from "@/components/Logo";
import { Button } from "@/components/ui/button";
import { Printer, ArrowLeft, Lock } from "lucide-react";
import { Link } from "wouter";
import { VisualReport } from "@/components/VisualReport";
import { track } from "@/lib/analytics";

/* PDF export gate.
 *
 * The user-facing "Save as PDF" affordance uses the browser's native
 * print dialog (window.print()) — robust, doesn't ship a heavy client-
 * side PDF library, and respects the operator's preferred page size /
 * orientation. The print stylesheet hides the app chrome and styles
 * the report for paper output.
 *
 * Export is GATED on the report being unlocked. A locked analysis has
 * a redacted body server-side (sanitizeAnalysisForResponse / lock
 * placeholder); even if a determined user printed the locked DOM they
 * would only get the redaction markers, but we still hide the button
 * to prevent confusion. The disclaimer is appended via a print-only
 * footer that always renders so the exported PDF is unambiguously
 * labeled as directional career-risk insight, not a guarantee.
 */
export default function Report() {
  const [, params] = useRoute("/report/:id");
  const id = params?.id ? Number(params.id) : null;
  const { data: analysis, isLoading } = useQuery<Analysis>({
    queryKey: ["/api/analyses", id],
    enabled: !!id,
  });
  const { data: me } = useQuery<User>({ queryKey: ["/api/me"] });

  if (isLoading || !analysis) {
    return (
      <div className="min-h-screen grid place-items-center text-muted-foreground">Loading report…</div>
    );
  }

  const isLocked = Boolean(analysis.is_locked);

  const onExport = () => {
    if (isLocked) return;
    track("report_pdf_export_clicked", { analysis_id: analysis.id });
    // Defer so the click animation completes before the modal opens.
    setTimeout(() => window.print(), 60);
  };

  return (
    <div className="min-h-screen bg-background">
      <div className="no-print sticky top-0 z-10 bg-background/90 backdrop-blur border-b border-border">
        <div className="max-w-5xl mx-auto px-6 py-3 flex items-center justify-between">
          <Link href="/history">
            <Button variant="ghost" size="sm" data-testid="button-report-back">
              <ArrowLeft className="w-4 h-4 mr-1.5" />
              Back
            </Button>
          </Link>
          <Logo size={22} />
          {isLocked ? (
            <Button size="sm" variant="outline" disabled data-testid="button-print-locked" title="Unlock the full report to export as PDF">
              <Lock className="w-4 h-4 mr-1.5" />
              Locked
            </Button>
          ) : (
            <Button onClick={onExport} size="sm" data-testid="button-print">
              <Printer className="w-4 h-4 mr-1.5" />
              Save as PDF
            </Button>
          )}
        </div>
      </div>

      <article className="max-w-5xl mx-auto px-4 sm:px-6 py-8 sm:py-10">
        <header className="mb-5 print-card text-xs uppercase tracking-widest text-muted-foreground flex flex-wrap gap-x-3 gap-y-1">
          <span className="text-gradient font-semibold">CareerProof AI</span>
          <span aria-hidden>·</span>
          <span>AI Impact Assessment</span>
          <span aria-hidden>·</span>
          <span>{toTitleCase(analysis.job_title)}</span>
          {me && (
            <>
              <span aria-hidden>·</span>
              <span>Prepared for {me.full_name}</span>
            </>
          )}
        </header>

        <VisualReport analysis={analysis} locked={isLocked} />

        <footer className="mt-10 pt-4 border-t border-border text-xs text-muted-foreground space-y-1">
          <div>
            Generated by CareerProof AI · {window.location.host} · {formatDateTime(analysis.created_date)}
          </div>
          <div className="italic">
            CareerProof AI provides directional career-risk insight to help you plan. It is not a
            prediction of the future and does not guarantee any specific employment outcome.
          </div>
        </footer>
      </article>

      {!isLocked && (
        <button
          className="no-print fixed bottom-6 right-6 rounded-full bg-primary text-primary-foreground shadow-lg px-4 py-2.5 text-sm font-medium flex items-center gap-2 hover-elevate"
          onClick={onExport}
          data-testid="button-print-floating"
        >
          <Printer className="w-4 h-4" />
          Print / Save as PDF
        </button>
      )}
    </div>
  );
}
