import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

/* =====================================================================
 * Users
 * Note: auth is simulated. A single "current user" row is bootstrapped
 * on first run. `role` controls credit behavior + admin UI.
 * ===================================================================== */
export const users = sqliteTable("users", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  full_name: text("full_name").notNull(),
  email: text("email").notNull().unique(),
  role: text("role").notNull().default("user"), // 'user' | 'admin'
  credits: integer("credits").notNull().default(0),
  created_date: text("created_date").notNull(), // ISO string
  // Server-side scrypt password hash (format: "scrypt$N$r$p$<saltHex>$<keyHex>").
  // Nullable so legacy / seeded rows can exist before the owner sets a password.
  // A user with a null hash must complete the first-time password setup flow
  // (POST /api/me/set-password) before they can sign in.
  password_hash: text("password_hash"),
});

export const insertUserSchema = createInsertSchema(users).omit({ id: true });
export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;

/* =====================================================================
 * Resumes
 * file_url is stored as either a relative server path or a data: URI
 * generated by the upload stub.
 * ===================================================================== */
export const resumes = sqliteTable("resumes", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  created_date: text("created_date").notNull(),
  created_by: integer("created_by").notNull(),
  filename: text("filename").notNull(),
  content_type: text("content_type").notNull(),
  file_url: text("file_url").notNull(),
  extracted_text: text("extracted_text").notNull(),
  size_bytes: integer("size_bytes").notNull(),
});

export const insertResumeSchema = createInsertSchema(resumes).omit({ id: true });
export type InsertResume = z.infer<typeof insertResumeSchema>;
export type Resume = typeof resumes.$inferSelect;

/* =====================================================================
 * Analyses
 * result_text is markdown; automation_risk is "High" | "Medium" | "Low"
 * provider_used identifies the model/source (e.g. "MockInvokeLLM")
 * ===================================================================== */
export const analyses = sqliteTable("analyses", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  created_date: text("created_date").notNull(),
  created_by: integer("created_by").notNull(),
  job_title: text("job_title").notNull(),
  job_description: text("job_description").notNull(),
  technology_context: text("technology_context"),
  resume_id: integer("resume_id"),
  result_text: text("result_text").notNull(),
  provider_used: text("provider_used").notNull(),
  automation_risk: text("automation_risk").notNull(), // High | Medium | Low
  risk_score: integer("risk_score").notNull(), // 1-100
  // Soft-lock flag: when a user with 0 credits runs an analysis the
  // record is created with is_locked=1. The frontend reveals the
  // headers / score gauge / banner but obfuscates the readable body
  // until the user buys credits or unlocks the report.
  is_locked: integer("is_locked", { mode: "boolean" }).notNull().default(false),
});

export const insertAnalysisSchema = createInsertSchema(analyses).omit({ id: true });
export type InsertAnalysis = z.infer<typeof insertAnalysisSchema>;
export type Analysis = typeof analyses.$inferSelect;

/* =====================================================================
 * Zod schemas used by API route handlers
 * ===================================================================== */
export const analyzeRequestSchema = z.object({
  job_title: z.string().min(1, "Job title is required"),
  job_description: z.string().min(1, "Job description is required"),
  technology_context: z.string().optional(),
  resume_id: z.number().optional().nullable(),
});
export type AnalyzeRequest = z.infer<typeof analyzeRequestSchema>;

export const autofillRequestSchema = z.object({
  job_title: z.string().min(1),
});
export type AutofillRequest = z.infer<typeof autofillRequestSchema>;

export const prefillFromResumeSchema = z.object({
  resume_id: z.number(),
});

/* =====================================================================
 * LinkedIn job import
 *
 * Accepts a LinkedIn job URL (e.g. https://www.linkedin.com/jobs/view/...)
 * and/or pasted text copied from a LinkedIn job page. The server attempts
 * to fetch the URL on a short timeout — many LinkedIn responses are
 * gated, partial, or return an auth wall, so the request must always
 * succeed even when fetching fails, and the response indicates which
 * source actually produced the parsed fields. If neither source yields
 * usable text the client is expected to fall back to manual entry.
 * ===================================================================== */
export const linkedinImportSchema = z
  .object({
    url: z
      .string()
      .trim()
      .max(2048, "URL is too long")
      .optional()
      .or(z.literal("")),
    pasted_text: z
      .string()
      .trim()
      .max(50_000, "Pasted text is too long")
      .optional()
      .or(z.literal("")),
  })
  .refine(
    (d) => Boolean((d.url && d.url.length) || (d.pasted_text && d.pasted_text.length)),
    { message: "Provide a LinkedIn URL or paste the job text." },
  );
export type LinkedInImportRequest = z.infer<typeof linkedinImportSchema>;

export const uploadResumeSchema = z.object({
  filename: z.string().min(1),
  content_type: z.string().min(1),
  size_bytes: z.number().int().nonnegative(),
  // data url with the file contents — generated by the browser; the
  // backend treats this as opaque storage. Real implementations would
  // proxy to S3 + an extraction service.
  data_url: z.string().min(1),
});
export type UploadResumeRequest = z.infer<typeof uploadResumeSchema>;

export const setCreditsSchema = z.object({
  user_id: z.number(),
  credits: z.number().int().nonnegative(),
});

/* =====================================================================
 * Payment package + checkout request
 *
 * Production note: this app uses a provider-agnostic abstraction (see
 * server/payments.ts → PaymentProvider). The recommended production
 * provider for simple digital credit packs is Stripe Checkout. For
 * merchant-of-record / global VAT handling, Lemon Squeezy or Paddle are
 * strong drop-in alternatives. Both fit the same PaymentProvider
 * interface — only the implementation file changes.
 * ===================================================================== */
export const createCheckoutSchema = z.object({
  package_id: z.string().min(1),
});
export type CreateCheckoutRequest = z.infer<typeof createCheckoutSchema>;

export const redeemPromoCodeSchema = z.object({
  code: z.string().min(1),
});

/* =====================================================================
 * Analysis feedback (post-preview survey)
 *
 * Posted from the FeedbackModal after a user views their free preview
 * or full report. The server pulls everything sensitive (email,
 * user_id, locked state, job title) from the authenticated session +
 * the referenced analysis row — the client only supplies the rating
 * and an optional comment.
 *
 * Anonymous users (no session) may also submit feedback; in that
 * case user_id/user_email are simply omitted from the outbound email.
 * ===================================================================== */
export const analysisFeedbackSchema = z.object({
  rating: z.number().int().min(1).max(5),
  comment: z.string().trim().max(2000).optional().or(z.literal("")),
  analysis_id: z.number().int().optional().nullable(),
});
export type AnalysisFeedbackRequest = z.infer<typeof analysisFeedbackSchema>;

/* =====================================================================
 * Credit ledger (durable transaction log)
 *
 * Every change to a user's credit balance — purchases, promo grants,
 * unlock spends, admin/manual adjustments — appends a row here. Rows
 * are immutable: corrections happen by writing a new row with an
 * opposite `amount_delta`, never by editing or deleting an existing
 * one. `balance_after` is the user's credit balance AT THAT POINT IN
 * THE LEDGER, so the most recent row's `balance_after` should match
 * `users.credits` for non-unlimited accounts.
 *
 * `reason` is a short machine-readable enum (purchase, promo,
 * unlock_spend, admin_adjustment). `reference` is a human-readable
 * label or external id (package id, promo code, analysis id, admin
 * note). `provider` is the payments provider that originated the row
 * for purchase rows; null for everything else.
 * ===================================================================== */
export const creditTransactions = sqliteTable("credit_transactions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  user_id: integer("user_id").notNull(),
  amount_delta: integer("amount_delta").notNull(),
  balance_after: integer("balance_after").notNull(),
  reason: text("reason").notNull(), // 'purchase' | 'promo' | 'unlock_spend' | 'admin_adjustment' | 'signup_bonus'
  reference: text("reference"), // package id, promo code, analysis id, etc.
  provider: text("provider"), // 'preview' | 'stripe' | 'lemonsqueezy' | null
  created_at: text("created_at").notNull(),
});
export type CreditTransaction = typeof creditTransactions.$inferSelect;
export type InsertCreditTransaction = Omit<CreditTransaction, "id">;

export const CREDIT_TX_REASONS = [
  "purchase",
  "promo",
  "unlock_spend",
  "admin_adjustment",
  "signup_bonus",
] as const;
export type CreditTxReason = (typeof CREDIT_TX_REASONS)[number];

/* =====================================================================
 * Auth request schemas
 * Password rules are deliberately modest for a preview app: at least 8
 * characters, must contain a letter and a digit. Tightening these in
 * production is encouraged.
 * ===================================================================== */
export const passwordSchema = z
  .string()
  .min(8, "Password must be at least 8 characters")
  .max(200, "Password is too long")
  .refine((v) => /[A-Za-z]/.test(v) && /\d/.test(v), {
    message: "Password must contain at least one letter and one number",
  });

export const signInRequestSchema = z.object({
  email: z.string().email("A valid email is required"),
  password: z.string().min(1, "Password is required"),
});
export type SignInRequest = z.infer<typeof signInRequestSchema>;

export const signUpRequestSchema = z
  .object({
    full_name: z.string().trim().min(1, "Name is required"),
    email: z.string().email("A valid email is required"),
    password: passwordSchema,
    confirm_password: z.string().min(1, "Please confirm your password"),
  })
  .refine((d) => d.password === d.confirm_password, {
    message: "Passwords do not match",
    path: ["confirm_password"],
  });
export type SignUpRequest = z.infer<typeof signUpRequestSchema>;

export const setPasswordRequestSchema = z
  .object({
    email: z.string().email("A valid email is required"),
    password: passwordSchema,
    confirm_password: z.string().min(1, "Please confirm your password"),
  })
  .refine((d) => d.password === d.confirm_password, {
    message: "Passwords do not match",
    path: ["confirm_password"],
  });
export type SetPasswordRequest = z.infer<typeof setPasswordRequestSchema>;

/* =====================================================================
 * Password reset flow
 *
 * 1. Client POSTs /api/me/forgot-password with {email}. The server
 *    always returns 200 with a generic message regardless of whether
 *    the email exists — this prevents account enumeration. If the
 *    email matches a real account, a short-lived single-use reset
 *    code is generated and stored.
 * 2. In a real deployment the code would be emailed to the user. This
 *    preview app has no email service, so the dev-affordance endpoint
 *    /api/me/forgot-password/preview-code (only available in dev or
 *    when ALLOW_PREVIEW_RESET_CODE=1) exposes the code for testing.
 * 3. Client POSTs /api/me/reset-password with {email, code, password,
 *    confirm_password}. On success the password_hash is replaced, the
 *    reset token is consumed, and the user is signed in.
 *
 * Codes are 6-digit numeric strings (zero-padded). They expire 30
 * minutes after issue and are single-use.
 * ===================================================================== */
export const passwordResets = sqliteTable("password_resets", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  user_id: integer("user_id").notNull(),
  // Hash of the issued code (NOT the plaintext code). We re-use scrypt
  // via the password hashing helper so a leaked password_resets table
  // does not directly hand out reset codes.
  code_hash: text("code_hash").notNull(),
  created_at: text("created_at").notNull(), // ISO
  expires_at: text("expires_at").notNull(), // ISO
  // ISO timestamp when the code was redeemed. Null means "still usable".
  used_at: text("used_at"),
});
export type PasswordReset = typeof passwordResets.$inferSelect;

export const forgotPasswordRequestSchema = z.object({
  email: z.string().email("A valid email is required"),
});
export type ForgotPasswordRequest = z.infer<typeof forgotPasswordRequestSchema>;

export const resetPasswordRequestSchema = z
  .object({
    email: z.string().email("A valid email is required"),
    code: z
      .string()
      .trim()
      .min(4, "Reset code is required")
      .max(64, "Reset code is too long"),
    password: passwordSchema,
    confirm_password: z.string().min(1, "Please confirm your password"),
  })
  .refine((d) => d.password === d.confirm_password, {
    message: "Passwords do not match",
    path: ["confirm_password"],
  });
export type ResetPasswordRequest = z.infer<typeof resetPasswordRequestSchema>;
